language: python
services:
  - postgres
addons:
  postgresql: "9.4"
sudo: required
# command to install dependencies
install: "pip install -r requirements.txt"
# make database before running scripts
before_script:
  - psql -c 'create database ngsewebsite;' -U postgres
# command to run tests
script:
  - python ./ngse/test.py
# services to use